#-------------------------------
# General Site Settings

baseURL = 'https://papaya-melba-984425.netlify.app/'
languageCode = 'en-us'
title = 'Yuri Cunha'
theme = 'menca'
googleAnalytics = "G-SKVX2E8KMF" # Add your identifier. For example UA-99631805-1.
paginate = 9


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events"
    weight = 3

  [[menu.main]]
    identifier = "contribute"
    name = "Contribute"
    url = "/contribute"
    weight = 4

  [[menu.main]]
    identifier = "uses"
    name = "Uses"
    url = "/uses"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 6

 


[params]
  logo = "/images/yuri.jpg" # You can add own logo. For example "/images/logo.png".
  description = "I write and operate database for a living."

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Yuri Cunha"
    author__bio = "Tech Writer, Database Programmer, Tea Enthusiast"
    author__avatar = "/images/yuri.jpg"

  [[params.social]]
    # icon = "ion-logo-mastodon"
    icon = "logo-mastodon"
    name = "Mastodon"
    link = "https://isyuricunha.social/@isyuricunha"

  [[params.social]]
    # icon = "ion-logo-github"
    icon = "logo-github"
    name = "GitHub"
    link = "https://github.com/isyuricunha"

  [[params.social]]
    # icon = "ion-logo-linkedin"
    icon = "logo-linkedin"
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/isyuricunha/"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Hey, I'm Yuri Cunha"
    hero__description = "Tech Writer, Database Programmer, Tea Enthusiast"
    hero__image = "/images/IMG_6321.jpeg"

  #-------------------------------
  # Gallery Footer Section
  [params.gallery]
    gallery__title = "Talk to Me About..."
    gallery__columns = 3 # You can change the number of gallery columns


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "f/xqkjjenb" # Add your formspree contact form. This is everything after https://formspree.io/

    # NOTE
    # Menca comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  # [params.disqus]
  #  disqusShortname = "demo-menca" # Add your shortname for Disqus Comment. For example demo-menca


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

